// for posts
export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_IF_NEEDED = 'FETCH_POSTS_IF_NEEDED'
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE'

export const CREATE_POST = 'CREATE_POST'
export const CREATE_POST_PENDING = 'CREATE_POST_PENDING'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE'

export const UPDATE_POST = 'UPDATE_POST'
export const UPDATE_POST_PENDING = 'UPDATE_POST_PENDING'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE'


// for users
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_IF_NEEDED = 'FETCH_USERS_IF_NEEDED'
export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_PENDING = 'DELETE_USER_PENDING'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_PENDING = 'CREATE_USER_PENDING'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USER_PENDING = 'UPDATE_USER_PENDING'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
